---
title: "Data Analysis for the Group Research Project"
toc: true
toc-location: right
---

# Overview

You are *either*

-   an integrated masters student doing BIO00088H Group Research Project
    *or*
-   an MSc Bioinformatics student doing BIO00070M Research, Professional
    and Team Skills

Data Analysis compromises five workshops covering computational skills.

All students do Core 1 (week 2) and Core 2 (week 6). In weeks 3, 4 and 5
BIO00088H students will do image analysis, structural analysis or
transcriptomics depending on their 88H project. MSc Bioinformatics
students do the Core workshops and the transcriptomics workshops as part
of BIO00070M.

| Week | Data Strand |
|----|----|
| 2 | Core 1 Supporting Information - reproducibility, project-oriented workflow, naming things, cool code, handy shortcuts |
| 3 | Strand specific 1 |
| 4 | Strand specific 2 |
| 5 | Strand specific 3 |
| 6 | Core 2 Supporting Information - documenting with a README, curating code, non-coded processes |

The 88H project types are:

| Title | Director | Data analysis strand |
|----|----|----|
| Investigating the differentiation of stem cells in healthy bone marrow | Jillian Barlow | Transcriptomics, Sandy Macdonald |
| Investigating  pathways involved in the Nickel detoxification in Willow | Liz Rylott | Transcriptomics, Sandy Macdonald |
| Investigating differential RNA expression through the Leishmania lifecycle | Pegine Walrad | Transcriptomics, Sandy Macdonald |
| Identifying novel proteins regulating synaptophagy | Richard Maguire | Image analysis, Richard Bingham |
| Defining pathological cascades in dopaminergic neurons in a Parkinson's model | Sean Sweeney | Image analysis, Richard Bingham |
| Discovery proteins for biotech applications: new classes of antibody mimetics | Michael Plevin | Structure Analysis, Jon Agirre |
| Designing isoform-selective Src kinase inhibitors | Gareth Evans | Structure Analysis, Jon Agirre |

70M students choose **one** on the transcriptomics data sets for their
poster.

## Module Learning Outcome linked to this content

Students who successfully complete this module will be able to

-   use appropriate computational techniques to reproducibly process,
    analyse and visualise data and generate scientific reports based on
    project work.

## What is this site for?

All material is on the VLE so why is this site useful? This site
collects everything together in a searchable way. The search icon is on
the top right.

## Please cite as

Rand E (2025). Data Analysis for Group Project.
https://3mmarand.github.io/BIO00088H-data/.

Pages made with R [@R-core], Quarto [@Allaire_Quarto_2024], `knitr`
[@knitr1; @knitr2; @knitr3], `kableExtra` [@kableExtra]
